#!/bin/sh
#
# @name Gazebo x500 D435i Vision
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_d435i}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# GCS 비연결 자율비행 기본값
param set-default NAV_DLL_ACT 0

# VINS Configuration
param set-default EKF2_MAG_TYPE 5
param set-default SYS_HAS_GPS 0
param set-default SIM_GPS_USED 0

# EKF2: fuse external vision (ORB-SLAM3 -> /fmu/in/vehicle_visual_odometry)
# for horizontal/vertical position, 3D velocity and yaw. Use vision as the
# height reference and disable GPS (warehouse / GPS-denied operation).
param set-default EKF2_EV_CTRL 15
param set-default EKF2_EV_DELAY 5
param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
